name: Utilgui
version: '${project.version}'
main: ferrevdd.utilgui.Utilgui
api-version: 1.18
commands:
  gui:
      description: opens the utility gui
  strike:
    description: strikes lightning at the cursor of the player
permissions:
  Util.*:
    description: for being able to use the gui
    default: op




