name: Utilgui
version: '${project.version}'
main: ferrevdd.utilgui.Utilgui
api-version: 1.18
commands:
  gui:
    description: opens the utility gui
    permissions:
      utilgui.use:
        description: Allows you to use the gui
        default: op

